version: "3.9"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/conf.d:/etc/nginx/conf.d"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./src:/var/www/html/"
    ports:
      - "80:80"
    networks:
      - internal
  php:
    image: nanoninja/php-fpm:latest
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./src:/var/www/html/"
    networks:
      - internal
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "popcat"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: "root"
      PMA_PASSWORD: ""
    restart: always
    ports:
      - "8950:80"
    networks:
      - internal
networks:
  internal:
    name: popX-internal
